### ISSUE TITLE
Add the MIT license on PyPi

### ISSUE THREAD

**Issue by MosheEichler** [norcuni/zipencrypt#3]
Hi, thanks for the very helpful package.
Could you please add the MIT license to [PyPI](https://pypi.org/pypi/zipencrypt/json) as well? Currently, it is missing

**Comment by devthat** [comment]
Hello @MosheEichler, thanks for cleaning this up.
Unfortunately I cannot release right now because I am on holidays and do not have access to my system. I will in 2 weeks though!
So you won't be seeing the update on pypi just yet.
